doctrine:
    orm:
        auto_generate_proxy_classes: false
        metadata_cache_driver:
            type: service
            id: doctrine.metadata_cache_provider
        query_cache_driver:
            type: service
            id: doctrine.query_cache_provider
        result_cache_driver:
            type: service
            id: doctrine.result_cache_provider
        second_level_cache:
            enabled: true
            log_enabled: true
            region_cache_driver:
                type: service
                id: doctrine.second_level_cache
services:
    doctrine.metadata_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.redis.cache'
    doctrine.query_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.redis.cache'
    doctrine.result_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.redis.cache'
    doctrine.second_level_cache:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.redis.cache'
